apiVersion: v1
# switch to data, if values to be provided base64-encoded
stringData:
  apiToken: <OPERATOR_TOKEN>
  dataIngestToken: <INGEST_TOKEN>
kind: Secret
metadata:
  name: {{{ .global.Rafay.ClusterName }}}
  namespace: dynatrace
  labels:
    dynatrace.com/created-by: "dynatrace.kubernetes"
type: Opaque